jms_security_extra:
    secure_all_services: false
    expressions: true

security:

    encoders:
        Rswork\AdminBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        rswork_admin:
            entity: { class: RsworkAdminBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        register:
            pattern:  ^/admin/user/(new|create)$
            security: false

        admin_login: 
            pattern:  ^/admin/login$
            security: false

        admin_area:
            pattern: ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
#- {path: ^/admin, roles: ROLE_ADMIN}
