rswork_admin_login:
    pattern:  /login
    defaults: { _controller: RsworkAdminBundle:Admin:login }

rswork_admin_login_check:
    pattern:  /login_check

RsworkAdminBundle_admin:
    resource: "@RsworkAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user
