parameters:
#    rswork_admin.example.class: Rswork\AdminBundle\Example

services:
#    rswork_admin.example:
#        class: %rswork_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
