parameters:
#    rswork_guestbook.example.class: Rswork\GuestbookBundle\Example

services:
#    rswork_guestbook.example:
#        class: %rswork_guestbook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
